exp_path: '/mnt/fs5/chpatel/test/test'
seed: 62
data:
  dataset_class: physion_particle
  physion_path: /ccn2/u/chpatel/physion_dataset/
  particle_type: rt_same_spacing
  graph_type: dpinet
  protocol: 'only_Dominoes'  # allbut_scenario, only_scenario, all
  split_percentage: 0.9
  skip: 3
  spacing: 0.033
train:
  batch_size : 1
  viz_after: 5000
  save_after: 5000
  log_after: 1000
  val_after: 1
  lr : 1.e-4
  weight_decay: 0.
  lr_scheduler: 'plateau'
  num_epochs : 10000
  accu_grad_batches: 2
  only_validate: False
eval:
  split: 'test'
  viz: False
model:
  model_name: dpinet
  ckpt_path: ''
  node_dim: 6
  node_attr_dim: 3
  rel_attr_dim: 1
  hidden_dim: 256
  num_stages: 4
  rot_type: 'quat' # 6d or quat
  impl_type: 'dpinet'
  out_type: 'vel'  # pos or vel
  invariant: False