exp_path: '/mnt/fs5/chpatel/test/test'
seed: 62
data:
  dataset_class: physion_particle
  physion_path: /ccn2/u/chpatel/physion_v2_hlink/
  particle_type: rt_same_spacing
  graph_type: invarnet
  protocol: 'only_Drop'  # allbut_scenario, only_scenario, all
  split_percentage: 0.9
  skip: 3
  spacing: 0.033
  f1_radius: 0.05
  remove_carpet: True
train:
  batch_size : 1
  viz_after: 5000
  save_after: 5000
  log_after: 1000
  val_after: 1
  lr : 1.e-4
  weight_decay: 0.
  lr_scheduler: 'plateau'
  num_epochs : 10000
  accu_grad_batches: 2
  only_validate: False
eval:
  split: 'test'
  viz: False
  outdir_prefix: 'viz'
model:
  model_name: invarnet
  ckpt_path: ''
  node_feat_dim: 6
  rel_feat_dim: 8
  hidden_dim: 128
  mp_rel_idx: [0, 0, 0, 1, 2, 3, 0, 0, 0]
  num_mp_blocks: 1
  effect_normalization: none